"""
Django settings for fss project.

Generated by 'django-admin startproject'.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

try:
    # pylint: disable=W0401,W0614
    from fss.local_settings import *
except ModuleNotFoundError as exc:
    # Only tolerate a genuinely-absent local_settings. A ModuleNotFoundError
    # raised by a bad import *inside* local_settings names that other module,
    # not fss.local_settings; re-raise it rather than booting with a half-built
    # configuration (e.g. no DATABASES) and a confusing downstream failure.
    if exc.name != 'fss.local_settings':
        raise

# Secure-by-default cookie posture. Site-specific settings may deliberately
# override these for local HTTP development, but production should not depend on
# each install having copied the latest local_settings.py template.
globals().setdefault('SESSION_COOKIE_SECURE', True)
globals().setdefault('CSRF_COOKIE_SECURE', True)
globals().setdefault('SESSION_COOKIE_SAMESITE', 'Lax')
globals().setdefault('CSRF_COOKIE_SAMESITE', 'Lax')
# Keep authenticated command authority within an operational shift. Saving on
# every request makes this an inactivity timeout rather than an absolute
# lifetime, while a session cookie prevents credentials persisting across a
# normal browser restart. Site-specific settings may deliberately tighten
# these defaults.
globals().setdefault('SESSION_COOKIE_AGE', 8 * 60 * 60)
globals().setdefault('SESSION_SAVE_EVERY_REQUEST', True)
globals().setdefault('SESSION_EXPIRE_AT_BROWSER_CLOSE', True)


def merge_csrf_trusted_origins(csrf_trusted, cors_allowed):
    """
    Every peer trusted for cross-origin CORS reads must also be CSRF-trusted
    for cross-origin command POSTs - in this multi-server design they are
    exactly the same peer set. A peer listed in CORS_ALLOWED_ORIGINS but not
    CSRF_TRUSTED_ORIGINS (as the README's multi-server example previously
    showed) lets cross-server polling work while silently 403ing cross-server
    commands.
    """
    return sorted(set(csrf_trusted) | set(cors_allowed))


# Union CORS peers into CSRF_TRUSTED_ORIGINS here, at the framework level, so
# the gap above can't recur regardless of which local_settings an install uses.
CSRF_TRUSTED_ORIGINS = merge_csrf_trusted_origins(
    globals().get('CSRF_TRUSTED_ORIGINS', []),
    globals().get('CORS_ALLOWED_ORIGINS', [])
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    with open(os.path.join(BASE_DIR, 'fss', 'secretkey.txt'), encoding='UTF-8') as f:
        SECRET_KEY = f.read().strip()

# Application definition

INSTALLED_APPS = [
    'config',
    'assets',
    'main',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fss.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fss.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'dist/'),
]

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# CORS: restrict to the two endpoints that remote FSS servers need to access.
# CORS_ALLOWED_ORIGINS must be set per deployment in local_settings.py.
# All peer servers must share a registered domain and be served over HTTPS.
CORS_URLS_REGEX = r'^/(current/all\.json|assets/\d+/command/(?:confirm|set))/$'
CORS_ALLOW_CREDENTIALS = True
