# Generated by Django 6.0.5 on 2026-05-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_assetstatus_bat_volt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
