# Generated by Django 6.0.5 on 2026-05-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_asset_name_unique"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="asset",
            name="assets_asse_name_e4d2fa_idx",
        ),
    ]
