# Generated by Django 6.0.6 on 2026-06-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_remove_asset_assets_asse_name_e4d2fa_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="assetcommand",
            name="assets_asse_asset_i_ccd558_idx",
        ),
        migrations.RemoveIndex(
            model_name="assetposition",
            name="assets_asse_asset_i_9e3456_idx",
        ),
        migrations.RemoveIndex(
            model_name="assetrtt",
            name="assets_asse_asset_i_9b46c0_idx",
        ),
        migrations.RemoveIndex(
            model_name="assetsearchprogress",
            name="assets_asse_asset_i_db9f9f_idx",
        ),
        migrations.RemoveIndex(
            model_name="assetstatus",
            name="assets_asse_asset_i_ef8e63_idx",
        ),
        migrations.AddIndex(
            model_name="assetcommand",
            index=models.Index(
                fields=["asset", "-timestamp"], name="assets_asse_asset_i_a1bf27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetposition",
            index=models.Index(
                fields=["asset", "-timestamp"], name="assets_asse_asset_i_ec5157_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetrtt",
            index=models.Index(
                fields=["asset", "-timestamp"], name="assets_asse_asset_i_23297b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetsearchprogress",
            index=models.Index(
                fields=["asset", "-timestamp"], name="assets_asse_asset_i_735fd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetstatus",
            index=models.Index(
                fields=["asset", "-timestamp"], name="assets_asse_asset_i_eb7df6_idx"
            ),
        ),
    ]
