# Generated by Django 6.0.6 on 2026-06-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_remove_assetcommand_assets_asse_asset_i_ccd558_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcommand",
            name="ack_state",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (0, "Received"),
                    (1, "Actioned"),
                    (2, "Superseded"),
                    (3, "Rejected"),
                    (4, "No change"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assetcommand",
            name="ack_superseded_by",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (0, "None"),
                    (1, "Low Battery"),
                    (2, "Comms Loss"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assetcommand",
            name="ack_timestamp",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetcommand",
            name="dispatch_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
