# Generated by Django 6.0.6 on 2026-06-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0008_assetcommand_ack_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetcommand",
            name="dispatch_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="assetcommand",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ack_superseded_by__isnull", True),
                    ("ack_superseded_by", 0),
                    ("ack_state", 2),
                    _connector="OR",
                ),
                name="ack_superseded_by_requires_superseded_state",
            ),
        ),
    ]
