# Generated by Django 6.0.7 on 2026-07-25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0010_assetcommand_issued_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCommandConfirmation",
            fields=[
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("command", models.CharField(choices=[("RTL", "Return to Launch"), ("HOLD", "Hold at Current Position"), ("GOTO", "Goto Position"), ("RON", "Continue"), ("DISARM", "Dis-Arm Aircraft"), ("ALT", "Adjust Altitude"), ("TERM", "Terminate Flight"), ("MAN", "Manual")], max_length=6)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
