# Generated by Django 6.0.7 on 2026-10-01 08:45

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0016_assetposition_gps_fix_valid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetIdentityEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "received_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("newcomer_rejected", "Newcomer rejected"),
                            ("incumbent_evicted", "Incumbent evicted"),
                        ],
                        max_length=24,
                    ),
                ),
                ("incumbent", models.JSONField(db_default={}, default=dict)),
                ("newcomer", models.JSONField(db_default={}, default=dict)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_username",
                    models.CharField(db_default="", default="", max_length=150),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="assets.asset"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["asset", "-id"], name="identity_event_history_idx"
                    ),
                    models.Index(
                        condition=models.Q(("acknowledged_at__isnull", True)),
                        fields=["asset", "-id"],
                        name="identity_event_pending_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("outcome__in", ["newcomer_rejected", "incumbent_evicted"])
                        ),
                        name="identity_event_valid_outcome",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("acknowledged_at__isnull", True),
                                ("acknowledged_by__isnull", True),
                                ("acknowledged_username", ""),
                            ),
                            models.Q(
                                ("acknowledged_at__isnull", False),
                                models.Q(("acknowledged_username", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="identity_event_ack_consistent",
                    ),
                ],
            },
        ),
    ]
