name: ESLint

on:
  pull_request:
  push:
    branches: [develop, main]
  workflow_call:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v7
     - name: Install modules
       run: npm ci
     - name: Run ESLint
       run: npm run check
     - name: Run tests
       run: npm test
